name: Update JSON Field

on:
  push:
    branches:
      - main

jobs:
  update_json_field:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          sudo apt-get install -y jq

      - name: Update JSON field
        run: |
          JSON=$(cat ./test.json)
          UPDATED_JSON=$(echo "$JSON" | jq '.instanceLabel = "api123"')
          echo "$UPDATED_JSON" > ./test.json
          echo "::set-output name=updated_json::$UPDATED_JSON"

      - name: Commit and push changes
        run: |
          git config --global user.name "nageshambati100"
          git config --global user.email "nageshambati100.com"
          git add ./test.json
          git commit -m "Update JSON field"
          git push
